spring.h2.console.path: "/h2/console"
spring.h2.console.enabled: true
debug: false
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name:  GRpc Demo
  profiles:
    active: local
  jpa:
    show-sql: true
#Log Configuration
logging:
  level:
    org:
      springframework: INFO
      apache:
        catalina: OFF
    springfox: OFF
    tech:
      central: INFO
system:
  name: Inventory Services
lombok:
  anyConstructor:
    addConstructorProperties: true
